import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/navbar'


export default function faq() {
  return (
    <>
      <Head>
        <title>FAQ - EarthCraft</title>
        <meta name="description" content="Earthcraft" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-[#292929]'>
    <Navbar />
    <p className='mt-[5vh] bg-mcbg1 bg-fixed bg-no-repeat bg-cover py-1 text-center text-white text-7xl tracking-widest' style={{fontFamily:"'Minecraftia', sans-serif"}}>FREQUENTLY ASKED QUESTIONS</p>
    <div className='mt-[20vh] flex'>
    <p className='mx-auto text-white font-extralight w-[60vw] text-center text-3xl'>
    Q: What is the server IP? <br />

A: The server IP is play.realearthcraft.com<br /><br />



Q: How large is the map?<br />

A: It&apos;s a 1 to 200 scale, which means 1 block is to 200 meters in real life. The map is around 186,000 blocks wide and is over 750GB in file size.<br /><br />



Q: Where can I download the map?<br />

A: Our map is not available to download. It was generated using EarthTiles a program created by MattiBorchers, our map was generated by FrenchFries8854 with the paid version of EarthTiles. You are welcome to create your own map using the EarthTiles program but we advise against this due to the time, performance and storage requirements.<br /><br />



Q: What version of Minecraft are we using?<br />

A: We use version 1.19.3<br /><br />



Q: How do I create/join a nation?<br />

A: Check out the Getting Started page for guidance on making the decision of whether to create or join. To create a nation follow the guide on this page. To join an existing nation go to this page.<br />
    </p>
        </div>
    <div className='pb-[150px]'></div>
    </div>
    </>
  )
}
